// Complete abilities library - Single source of truth for all abilities
// Organized by class and specialization
// Includes all classes, specs, and ultimate abilities

export type AbilityKind = 'attack' | 'buff' | 'debuff' | 'utility' | 'ultimate' | 'passive' | 'heal'
export type AbilityCategory = 'class' | 'spec' | 'base' | 'ultimate'
export type StatScaling =
  | 'atk' | 'def' | 'spd' | 'hp' // Single stat
  | 'max_atk_def' | 'max_atk_spd' | 'max_def_spd' // Max of two stats
  | 'avg_atk_def' | 'avg_atk_spd' | 'avg_def_spd' // Average of two stats
  | 'fixed' // Fixed value (damageMultiplier used directly)

export interface AbilityDefinition {
  id: string
  name: string
  icon: string
  emoji: string
  kind: AbilityKind
  category: AbilityCategory
  cooldown: number
  damageMultiplier: number
  statScaling: StatScaling // How ability scales from dino stats
  effects: string[] // Array of effect IDs, 'none' to skip
  description: string
  fullDescription: string
  isPassive?: boolean
  isVampiric?: boolean // Lifesteal ability
}

export interface ClassAbilities {
  id: string
  name: string
  emoji: string
  description: string
  abilities: AbilityDefinition[]
}

export interface SpecAbilities {
  id: string
  name: string
  emoji: string
  description: string
  classId: string
  abilities: AbilityDefinition[]
}

// ============= CLASS ABILITIES =============

export const CLASS_ABILITIES: Record<string, ClassAbilities> = {
  big_carnivore: {
    id: 'big_carnivore',
    name: 'Büyük Yırtıcı',
    emoji: '🦖',
    description: 'Güçlü ve tehlikeli, ağır saldırılara sahip.',
    abilities: [
      {
        id: 'claw',
        name: 'Pençe',
        icon: 'claw',
        emoji: '🐾',
        kind: 'attack',
        category: 'class',
        cooldown: 0,
        damageMultiplier: 1,
        statScaling: 'atk',
        effects: [],
        description: 'Her tur atılabilen standart hasar',
        fullDescription: 'Temel saldırı. Her turda kullanılabilir, standart hasar verir.',
      },
      {
        id: 'bite',
        name: 'Isırma',
        icon: 'bite',
        emoji: '😈',
        kind: 'attack',
        category: 'class',
        cooldown: 3,
        damageMultiplier: 1.2,
        statScaling: 'atk',
        effects: ['bleeding'],
        description: '3 turda bir, hasar + kanama efektli',
        fullDescription: 'Güçlü bir ısırma. Hasar verir ve kanama efekti uygular.',
      },
      {
        id: 'pounce',
        name: 'Üstüne Çıkma',
        icon: 'pounce',
        emoji: '⚡',
        kind: 'attack',
        category: 'class',
        cooldown: 3,
        damageMultiplier: 0.8,
        statScaling: 'atk',
        effects: ['stun'],
        description: '3 turda bir, az hasar + sersemletme efektli',
        fullDescription: 'Hızlı bir hamle. Daha az hasar verir ama sersem efekti uygular.',
      },
      {
        id: 'roar',
        name: 'Korkunç Bağırma',
        icon: 'roar',
        emoji: '📢',
        kind: 'debuff',
        category: 'class',
        cooldown: 2,
        damageMultiplier: 0,
        statScaling: 'atk',
        effects: ['defense_down'],
        description: '2 turda bir, 0 hasar ama -savunma efektli',
        fullDescription: 'Korkutucu bir bağırış. Rakibin savunmasını düşürür.',
      },
      {
        id: 'tail_whip',
        name: 'Kuyruk Vurma',
        icon: 'tail',
        emoji: '💫',
        kind: 'attack',
        category: 'class',
        cooldown: 0,
        damageMultiplier: 0.9,
        statScaling: 'atk',
        effects: [],
        description: 'Her tur atılabilen orta hasar',
        fullDescription: 'Kuyrakla hızlı bir vurma. Her turda kullanılabilir.',
      },
    ],
  },

  raptor: {
    id: 'raptor',
    name: 'Raptor',
    emoji: '🦅',
    description: 'Hızlı ve çevik, sık saldırılara sahip.',
    abilities: [
      {
        id: 'slash',
        name: 'Kesici Pençe',
        icon: 'slash',
        emoji: '✂️',
        kind: 'attack',
        category: 'class',
        cooldown: 0,
        damageMultiplier: 0.8,
        statScaling: 'max_atk_spd',
        effects: [],
        description: 'Her tur atılabilen hafif hasar',
        fullDescription: 'Hızlı ve keskin bir saldırı. Her turda kullanılabilir.',
      },
      {
        id: 'toxic_spit',
        name: 'Zehirli Tükürme',
        icon: 'spit',
        emoji: '☠️',
        kind: 'attack',
        category: 'class',
        cooldown: 2,
        damageMultiplier: 0.6,
        statScaling: 'max_atk_spd',
        effects: ['poison'],
        description: '2 turda bir, hafif hasar + zehir efektli',
        fullDescription: 'Zehirli tükürük saçar. Azda olsa hasar verir ve zehir efekti uygular.',
      },
      {
        id: 'dodge',
        name: 'Kaçış',
        icon: 'dodge',
        emoji: '💨',
        kind: 'utility',
        category: 'class',
        cooldown: 2,
        damageMultiplier: 0,
        statScaling: 'spd',
        effects: [],
        description: '2 turda bir, sonraki hasarı azaltır',
        fullDescription: 'Hızlı bir kaçış hareketi. Bir sonraki hasarı yarıya indirir.',
      },
      {
        id: 'leap_attack',
        name: 'Sıçrama Saldırısı',
        icon: 'leap',
        emoji: '🚀',
        kind: 'attack',
        category: 'class',
        cooldown: 2,
        damageMultiplier: 1.1,
        statScaling: 'max_atk_spd',
        effects: [],
        description: '2 turda bir, orta hasar',
        fullDescription: 'Yüksek sıçrama yaparak saldırır. Orta derecede hasar verir.',
      },
      {
        id: 'scratch',
        name: 'Tırmaklama',
        icon: 'scratch',
        emoji: '🪓',
        kind: 'attack',
        category: 'class',
        cooldown: 1,
        damageMultiplier: 0.7,
        statScaling: 'max_atk_spd',
        effects: [],
        description: '1 turda bir, hafif hasar',
        fullDescription: 'Hızlı tırmalama hareketi. Sık kullanılabilir.',
      },
    ],
  },

  giant_herbivore: {
    id: 'giant_herbivore',
    name: 'Dev Otçul',
    emoji: '🦣',
    description: 'Devasa ve dayanıklı, savunma ve iyileştirme odaklı.',
    abilities: [
      {
        id: 'stomp',
        name: 'Ayak Basma',
        icon: 'stomp',
        emoji: '👣',
        kind: 'attack',
        category: 'class',
        cooldown: 0,
        damageMultiplier: 1.3,
        statScaling: 'max_atk_def',
        effects: [],
        description: 'Her tur atılabilen güçlü hasar',
        fullDescription: 'Ağır bir ayak basması. Her turda kullanılabilir, yüksek hasar verir.',
      },
      {
        id: 'charge',
        name: 'Hücum',
        icon: 'charge',
        emoji: '🏃',
        kind: 'attack',
        category: 'class',
        cooldown: 4,
        damageMultiplier: 1.8,
        statScaling: 'max_atk_def',
        effects: [],
        description: '4 turda bir, çok yüksek hasar',
        fullDescription: 'Hızla koşarak hücum eder. Çok yüksek hasar verir.',
      },
      {
        id: 'brace',
        name: 'Hazırlanma',
        icon: 'brace',
        emoji: '🛡️',
        kind: 'buff',
        category: 'class',
        cooldown: 2,
        damageMultiplier: 0,
        statScaling: 'def',
        effects: ['shield'],
        description: '2 turda bir, +savunma efektli',
        fullDescription: 'Vücudunu hazırlar. Savunması artar.',
      },
      {
        id: 'shake',
        name: 'Çalkalanma',
        icon: 'shake',
        emoji: '🌊',
        kind: 'debuff',
        category: 'class',
        cooldown: 3,
        damageMultiplier: 0.5,
        statScaling: 'def',
        effects: [],
        description: '3 turda bir, hafif hasar',
        fullDescription: 'Güçlü bir sallanma ile çevre yer sarsar.',
      },
      {
        id: 'head_butt',
        name: 'Kafa Bufesi',
        icon: 'headbutt',
        emoji: '🤕',
        kind: 'attack',
        category: 'class',
        cooldown: 2,
        damageMultiplier: 1.4,
        statScaling: 'max_atk_def',
        effects: [],
        description: '2 turda bir, yüksek hasar',
        fullDescription: 'Başıyla sert bir darbe iner.',
      },
    ],
  },

  flying_carnivore: {
    id: 'flying_carnivore',
    name: 'Uçan Yırtıcı',
    emoji: '🪶',
    description: 'Hızlı ve çevik, hava üstünlüğü sağlayan.',
    abilities: [
      {
        id: 'aerial_strike',
        name: 'Hava Saldırısı',
        icon: 'aerial',
        emoji: '⚔️',
        kind: 'attack',
        category: 'class',
        cooldown: 0,
        damageMultiplier: 1.0,
        statScaling: 'max_atk_spd',
        effects: [],
        description: 'Her tur atılabilen standart hasar',
        fullDescription: 'Havadan yapılan hızlı saldırı. Her turda kullanılabilir.',
      },
      {
        id: 'dive_bomb',
        name: 'Dalış Saldırısı',
        icon: 'dive',
        emoji: '💣',
        kind: 'attack',
        category: 'class',
        cooldown: 3,
        damageMultiplier: 1.5,
        statScaling: 'max_atk_spd',
        effects: [],
        description: '3 turda bir, yüksek hasar',
        fullDescription: 'Yüksekten dibe dalarak saldırır. Çok hasar verir.',
      },
      {
        id: 'wind_gust',
        name: 'Rüzgar Akını',
        icon: 'wind',
        emoji: '💨',
        kind: 'debuff',
        category: 'class',
        cooldown: 2,
        damageMultiplier: 0.3,
        statScaling: 'spd',
        effects: [],
        description: '2 turda bir, az hasar',
        fullDescription: 'Güçlü bir rüzgar akını yaratır.',
      },
      {
        id: 'swoop',
        name: 'Dönüş Hareketi',
        icon: 'swoop',
        emoji: '🌪️',
        kind: 'attack',
        category: 'class',
        cooldown: 1,
        damageMultiplier: 0.85,
        statScaling: 'max_atk_spd',
        effects: [],
        description: '1 turda bir, hafif hasar',
        fullDescription: 'Hızlı bir dönüş hareketi ile saldırır.',
      },
      {
        id: 'peck',
        name: 'Gagalama',
        icon: 'peck',
        emoji: '🐦',
        kind: 'attack',
        category: 'class',
        cooldown: 0,
        damageMultiplier: 0.6,
        statScaling: 'max_atk_spd',
        effects: [],
        description: 'Her tur atılabilen hafif hasar',
        fullDescription: 'Gagası ile hızlı bir saldırı. Her turda kullanılabilir.',
      },
    ],
  },
}

// ============= SPEC ABILITIES =============

export const SPEC_ABILITIES: Record<string, SpecAbilities> = {
  // Big Carnivore Specs
  armored: {
    id: 'armored',
    name: 'Kalkanlı',
    emoji: '🛡️',
    description: 'Zırhlı vücut, savunma odaklı.',
    classId: 'big_carnivore',
    abilities: [
      {
        id: 'armor_up',
        name: 'Zırhlan',
        icon: 'armor',
        emoji: '⚙️',
        kind: 'buff',
        category: 'spec',
        cooldown: 4,
        damageMultiplier: 0,
        statScaling: 'def',
        effects: ['shield'],
        description: '4 turda bir, +savunma 3 tur boyunca',
        fullDescription: 'Zırh aktivasyonu. 3 tur boyunca savunması artar.',
      },
      {
        id: 'protect',
        name: 'Korunma',
        icon: 'protect',
        emoji: '🔒',
        kind: 'utility',
        category: 'spec',
        cooldown: 5,
        damageMultiplier: 0,
        statScaling: 'def',
        effects: [],
        description: '5 turda bir, sonraki saldırıdan tamamen korur',
        fullDescription: 'Savunma pozisyonu. Bir sonraki saldırıyı tamamen engeller.',
      },
      {
        id: 'spiky_armor',
        name: 'Dikenli Zırh',
        icon: 'spiky',
        emoji: '🔱',
        kind: 'passive',
        category: 'spec',
        cooldown: 0,
        damageMultiplier: 0,
        statScaling: 'def',
        effects: [],
        isPassive: true,
        description: 'Pasif, direkt hasarın %2 sini geri yansıtır',
        fullDescription: 'Zırh üzerinde dikenleri vardır. Aldığı direkt hasarın %2 sini yansıtır.',
      },
    ],
  },

  fire_spec: {
    id: 'fire_spec',
    name: 'Ateşli',
    emoji: '🔥',
    description: 'Ateş yetenekleri, agresif saldırılar.',
    classId: 'big_carnivore',
    abilities: [
      {
        id: 'fire_breath',
        name: 'Ateş Nefesi',
        icon: 'fire',
        emoji: '🔥',
        kind: 'attack',
        category: 'spec',
        cooldown: 3,
        damageMultiplier: 1.3,
        statScaling: 'atk',
        effects: [],
        description: '3 turda bir, yüksek hasar',
        fullDescription: 'Ateş soluması. Yüksek hasar verir.',
      },
      {
        id: 'flame_burst',
        name: 'Alev Patlaması',
        icon: 'burst',
        emoji: '💥',
        kind: 'attack',
        category: 'spec',
        cooldown: 4,
        damageMultiplier: 1.6,
        statScaling: 'atk',
        effects: [],
        description: '4 turda bir, çok yüksek hasar',
        fullDescription: 'Kontrollü bir patlama. Büyük hasar verir.',
      },
      {
        id: 'heat_aura',
        name: 'Isı Auraşı',
        icon: 'aura',
        emoji: '♨️',
        kind: 'buff',
        category: 'spec',
        cooldown: 2,
        damageMultiplier: 0,
        statScaling: 'atk',
        effects: ['power'],
        description: '2 turda bir, +hasar efektli',
        fullDescription: 'Isı enerjisi artışı. Saldırı gücü artar.',
      },
    ],
  },

  ultra_carnivore: {
    id: 'ultra_carnivore',
    name: 'Ultra Yırtıcı',
    emoji: '👹',
    description: 'Agresif ve vahşi, saldırı odaklı.',
    classId: 'big_carnivore',
    abilities: [
      {
        id: 'frenzy',
        name: 'Çılgınlık',
        icon: 'frenzy',
        emoji: '😡',
        kind: 'buff',
        category: 'spec',
        cooldown: 3,
        damageMultiplier: 0,
        statScaling: 'atk',
        effects: ['power'],
        description: '3 turda bir, +hasar efektli',
        fullDescription: 'Vahşi bir çılgınlık modu. Saldırı gücü artar.',
      },
      {
        id: 'savage_strike',
        name: 'Vahşi Darbe',
        icon: 'savage',
        emoji: '🩸',
        kind: 'attack',
        category: 'spec',
        cooldown: 2,
        damageMultiplier: 1.7,
        statScaling: 'atk',
        effects: ['bleeding'],
        description: '2 turda bir, yüksek hasar + kanama',
        fullDescription: 'Vahşice bir saldırı. Yüksek hasar ve kanama efekti verir.',
      },
      {
        id: 'bloodlust',
        name: 'Kan Hortumu',
        icon: 'bloodlust',
        emoji: '🧛',
        kind: 'heal',
        category: 'spec',
        cooldown: 4,
        damageMultiplier: 0.9,
        statScaling: 'atk',
        effects: [],
        description: '4 turda bir, hasarı %50 inin geri kazanır',
        fullDescription: 'Rakibinin kanını içerek hasar verir ve aldığı hasarın %50sini HP olarak geri kazanır.',
        // @ts-ignore - vampiric flag for BattleEngine
        isVampiric: true,
      },
    ],
  },

  // Raptor Specs
  speed_demon: {
    id: 'speed_demon',
    name: 'Hız Şeytanı',
    emoji: '⚡',
    description: 'Müthiş hız, her turda saldırı yapabilir.',
    classId: 'raptor',
    abilities: [
      {
        id: 'blitz_attack',
        name: 'Yıldırım Saldırısı',
        icon: 'speed',
        emoji: '⚡',
        kind: 'attack',
        category: 'spec',
        cooldown: 0,
        damageMultiplier: 0.95,
        statScaling: 'max_atk_spd',
        effects: [],
        description: 'Her tur atılabilen orta hasar',
        fullDescription: 'Işık hızında saldırı. Her turda kullanılabilir, orta hasar verir.',
      },
      {
        id: 'turbo_charge',
        name: 'Turbo Şarj',
        icon: 'speed',
        emoji: '🏎️',
        kind: 'buff',
        category: 'spec',
        cooldown: 3,
        damageMultiplier: 0,
        statScaling: 'spd',
        effects: ['speed'],
        description: '3 turda bir, +hız efektli',
        fullDescription: 'Hızını maksimuma çıkarır. Hareket hızı artar.',
      },
      {
        id: 'temporal_advantage',
        name: 'Zamansal Üstünlük',
        icon: 'speed',
        emoji: '🌀',
        kind: 'utility',
        category: 'spec',
        cooldown: 5,
        damageMultiplier: 0,
        statScaling: 'spd',
        effects: [],
        description: '5 turda bir, bir ekstra tur alır',
        fullDescription: 'Zaman akışını kontrol eder. Ekstra bir tur daha saldırır.',
      },
    ],
  },

  poison_master: {
    id: 'poison_master',
    name: 'Zehir Ustası',
    emoji: '☠️',
    description: 'Zehir yetenekleri, ölümcül toksinler.',
    classId: 'raptor',
    abilities: [
      {
        id: 'toxic_cloud',
        name: 'Zehirli Bulut',
        icon: 'poison',
        emoji: '☠️',
        kind: 'debuff',
        category: 'spec',
        cooldown: 2,
        damageMultiplier: 0.2,
        statScaling: 'atk',
        effects: ['poison'],
        description: '2 turda bir, az hasar + zehir',
        fullDescription: 'Zehirli gaz bulut. Rakibi zehirler.',
      },
      {
        id: 'neurotoxin',
        name: 'Nörotoksin',
        icon: 'paralyze',
        emoji: '🧬',
        kind: 'debuff',
        category: 'spec',
        cooldown: 4,
        damageMultiplier: 0,
        statScaling: 'atk',
        effects: ['paralyze'],
        description: '4 turda bir, paralyze efektli',
        fullDescription: 'Sinir sistemini felç eden zehir. Paralizi nedeni olur.',
      },
      {
        id: 'antidote_mastery',
        name: 'Antidot Uzmanı',
        icon: 'heal',
        emoji: '💉',
        kind: 'heal',
        category: 'spec',
        cooldown: 3,
        damageMultiplier: 0,
        statScaling: 'def',
        effects: ['heal'],
        description: '3 turda bir, kendini iyileştirir',
        fullDescription: 'Antioksidanlar ile kendini iyileştirir. HP kazanır.',
      },
    ],
  },

  pack_hunter: {
    id: 'pack_hunter',
    name: 'Sürü Avcısı',
    emoji: '👥',
    description: 'Taktikli saldırılar, koordineli hamle.',
    classId: 'raptor',
    abilities: [
      {
        id: 'coordinated_strike',
        name: 'Koordine Saldırısı',
        icon: 'slash',
        emoji: '⚔️',
        kind: 'attack',
        category: 'spec',
        cooldown: 2,
        damageMultiplier: 1.2,
        statScaling: 'max_atk_spd',
        effects: [],
        description: '2 turda bir, orta-yüksek hasar',
        fullDescription: 'Taktiğe dayalı saldırı. Ortadüzey yüksek hasar verir.',
      },
      {
        id: 'pack_tactics',
        name: 'Sürü Taktikleri',
        icon: 'dodge',
        emoji: '🛡️',
        kind: 'buff',
        category: 'spec',
        cooldown: 2,
        damageMultiplier: 0,
        statScaling: 'def',
        effects: ['shield'],
        description: '2 turda bir, +savunma ve +hız',
        fullDescription: 'Sürü düzenine girer. Savunma ve hız artar.',
      },
      {
        id: 'predatory_instinct',
        name: 'Avcı İçgüdüsü',
        icon: 'bite',
        emoji: '🦁',
        kind: 'passive',
        category: 'spec',
        cooldown: 0,
        damageMultiplier: 0,
        statScaling: 'atk',
        effects: [],
        isPassive: true,
        description: 'Pasif, zayıf rakiplere %15 daha çok hasar',
        fullDescription: 'Avcı içgüdüsü kırmızı görmesine sebep olur. Zayıf rakiplere ekstra hasar.',
      },
    ],
  },

  // Giant Herbivore Specs
  tank: {
    id: 'tank',
    name: 'Tank',
    emoji: '🏰',
    description: 'Son derece dayanıklı, koruma uzmanı.',
    classId: 'giant_herbivore',
    abilities: [
      {
        id: 'fortify',
        name: 'Takviye',
        icon: 'brace',
        emoji: '🏰',
        kind: 'buff',
        category: 'spec',
        cooldown: 2,
        damageMultiplier: 0,
        statScaling: 'def',
        effects: ['shield'],
        description: '2 turda bir, +savunma %60',
        fullDescription: 'Vücudunu demir kabuğu gibi yapır. Savunması çok artar.',
      },
      {
        id: 'last_stand',
        name: 'Son Direniş',
        icon: 'protect',
        emoji: '💪',
        kind: 'utility',
        category: 'spec',
        cooldown: 6,
        damageMultiplier: 0,
        statScaling: 'def',
        effects: [],
        description: '6 turda bir, hasarı %80 azaltır',
        fullDescription: 'Son bir çabada hasarı neredeyse tamamen bloke eder.',
      },
      {
        id: 'iron_body',
        name: 'Demir Vücut',
        icon: 'spiky',
        emoji: '⚔️',
        kind: 'passive',
        category: 'spec',
        cooldown: 0,
        damageMultiplier: 0,
        statScaling: 'def',
        effects: [],
        isPassive: true,
        description: 'Pasif, aldığı hasarın %3 ünü geri yansıtır',
        fullDescription: 'Vücudu demir gibi sert. Her hasardan geri vurur.',
      },
    ],
  },

  healer: {
    id: 'healer',
    name: 'İyileştirici',
    emoji: '💚',
    description: 'Doğal iyileştirme, yaşam kaynağı.',
    classId: 'giant_herbivore',
    abilities: [
      {
        id: 'nurture',
        name: 'Beslenme',
        icon: 'heal',
        emoji: '🌿',
        kind: 'heal',
        category: 'spec',
        cooldown: 2,
        damageMultiplier: 0,
        statScaling: 'def',
        effects: ['heal'],
        description: '2 turda bir, kendini iyileştirir',
        fullDescription: 'Doğal gücü ile kendini besler. HP kazanır.',
      },
      {
        id: 'natural_recovery',
        name: 'Doğal İyileşme',
        icon: 'regenerate',
        emoji: '🌱',
        kind: 'heal',
        category: 'spec',
        cooldown: 3,
        damageMultiplier: 0,
        statScaling: 'def',
        effects: ['regen'],
        description: '3 turda bir, sürekli iyileşme 3 turlu',
        fullDescription: 'Doğa ile bağlantı kurur. 3 tur boyunca her tur iyileşir.',
      },
      {
        id: 'symbiotic_bond',
        name: 'Sembiyo Bağı',
        icon: 'barrier',
        emoji: '🌳',
        kind: 'buff',
        category: 'spec',
        cooldown: 4,
        damageMultiplier: 0,
        statScaling: 'def',
        effects: ['shield'],
        description: '4 turda bir, +savunma + iyileşme',
        fullDescription: 'Çevre ile bağlantı kurar. Savunma artar ve iyileşir.',
      },
    ],
  },

  earth_shaker: {
    id: 'earth_shaker',
    name: 'Yer Sarsıcısı',
    emoji: '⛏️',
    description: 'Yer gücü, sarsıntı saldırıları.',
    classId: 'giant_herbivore',
    abilities: [
      {
        id: 'ground_slam',
        name: 'Yer Darbesi',
        icon: 'stomp',
        emoji: '⛏️',
        kind: 'attack',
        category: 'spec',
        cooldown: 2,
        damageMultiplier: 1.5,
        statScaling: 'max_atk_def',
        effects: [],
        description: '2 turda bir, yüksek hasar',
        fullDescription: 'Yeri güçlü şekilde darbeleme. Yüksek hasar verir.',
      },
      {
        id: 'earthquake',
        name: 'Deprem',
        icon: 'shake',
        emoji: '🌍',
        kind: 'debuff',
        category: 'spec',
        cooldown: 5,
        damageMultiplier: 1.3,
        statScaling: 'max_atk_def',
        effects: ['paralyze'],
        description: '5 turda bir, hasar + paralyze',
        fullDescription: 'Büyük deprem yaratır. Hasar verir ve paralizr eder.',
      },
      {
        id: 'earth_blessing',
        name: 'Yer Mübarekleri',
        icon: 'barrier',
        emoji: '🪨',
        kind: 'buff',
        category: 'spec',
        cooldown: 3,
        damageMultiplier: 0,
        statScaling: 'def',
        effects: ['shield'],
        description: '3 turda bir, +savunma',
        fullDescription: 'Yer enerjisini çekerek koruma sağlar.',
      },
    ],
  },

  // Flying Carnivore Specs
  storm_bringer: {
    id: 'storm_bringer',
    name: 'Fırtına Getirici',
    emoji: '⛈️',
    description: 'Fırtına yetenekleri, elektrik saldırıları.',
    classId: 'flying_carnivore',
    abilities: [
      {
        id: 'lightning_strike',
        name: 'Yıldırım Darbe',
        icon: 'paralyze',
        emoji: '⚡',
        kind: 'attack',
        category: 'spec',
        cooldown: 3,
        damageMultiplier: 1.4,
        statScaling: 'max_atk_spd',
        effects: ['paralyze'],
        description: '3 turda bir, hasar + paralyze',
        fullDescription: 'Gökyüzünden yıldırım çeker. Hasar verir ve paralizr eder.',
      },
      {
        id: 'storm_surge',
        name: 'Fırtına Dalgası',
        icon: 'wind',
        emoji: '🌪️',
        kind: 'debuff',
        category: 'spec',
        cooldown: 4,
        damageMultiplier: 1.2,
        statScaling: 'max_atk_spd',
        effects: [],
        description: '4 turda bir, hasar + rakip savunma düşüyor',
        fullDescription: 'Güçlü fırtına dalgası yaratır. Hasar ve savunma düşürür.',
      },
      {
        id: 'static_field',
        name: 'Statik Alan',
        icon: 'aura',
        emoji: '⚡',
        kind: 'passive',
        category: 'spec',
        cooldown: 0,
        damageMultiplier: 0,
        statScaling: 'spd',
        effects: [],
        isPassive: true,
        description: 'Pasif, elektrik alanı rakip hızını %20 azaltır',
        fullDescription: 'Vücudu elektrik ile dolu. Yaklaşan rakipleri yavaşlatır.',
      },
    ],
  },

  wind_dancer: {
    id: 'wind_dancer',
    name: 'Rüzgar Dansçısı',
    emoji: '🌪️',
    description: 'Rüzgar kontrolü, kaçış ve hız.',
    classId: 'flying_carnivore',
    abilities: [
      {
        id: 'wind_slash',
        name: 'Rüzgar Kesisi',
        icon: 'slash',
        emoji: '🌪️',
        kind: 'attack',
        category: 'spec',
        cooldown: 1,
        damageMultiplier: 0.9,
        statScaling: 'max_atk_spd',
        effects: [],
        description: '1 turda bir, orta hasar',
        fullDescription: 'Rüzgarla saldırır. Sık kullanılabilir.',
      },
      {
        id: 'evasion_wind',
        name: 'Kaçış Rüzgarı',
        icon: 'dodge',
        emoji: '💨',
        kind: 'buff',
        category: 'spec',
        cooldown: 2,
        damageMultiplier: 0,
        statScaling: 'spd',
        effects: ['speed'],
        description: '2 turda bir, +hız, saldırı kaçırma şansı',
        fullDescription: 'Rüzgarla kendini korur. Hız artar ve saldırı kaçarabilir.',
      },
      {
        id: 'wind_current',
        name: 'Rüzgar Akımı',
        icon: 'wind',
        emoji: '🌬️',
        kind: 'utility',
        category: 'spec',
        cooldown: 3,
        damageMultiplier: 0,
        statScaling: 'spd',
        effects: [],
        description: '3 turda bir, saldırı hasarını %30 azaltır',
        fullDescription: 'Akıllı rüzgar akımı yaratır. Gelen hasarı büyük oranda azaltır.',
      },
    ],
  },

  sun_striker: {
    id: 'sun_striker',
    name: 'Güneş Darbesi',
    emoji: '☀️',
    description: 'Güneş gücü, ışın saldırıları.',
    classId: 'flying_carnivore',
    abilities: [
      {
        id: 'solar_flare',
        name: 'Güneş Alev',
        icon: 'fire',
        emoji: '☀️',
        kind: 'attack',
        category: 'spec',
        cooldown: 2,
        damageMultiplier: 1.3,
        statScaling: 'max_atk_spd',
        effects: [],
        description: '2 turda bir, yüksek hasar',
        fullDescription: 'Güneş enerji patlaması. Yüksek hasar verir.',
      },
      {
        id: 'daylight_buff',
        name: 'Gündüz Gücü',
        icon: 'aura',
        emoji: '⭐',
        kind: 'buff',
        category: 'spec',
        cooldown: 3,
        damageMultiplier: 0,
        statScaling: 'atk',
        effects: ['power'],
        description: '3 turda bir, +hasar',
        fullDescription: 'Güneş enerjisini emip güçlenir. Saldırı gücü artar.',
      },
      {
        id: 'solar_shield',
        name: 'Güneş Kalkanı',
        icon: 'barrier',
        emoji: '🌞',
        kind: 'buff',
        category: 'spec',
        cooldown: 4,
        damageMultiplier: 0,
        statScaling: 'def',
        effects: ['shield', 'regen'],
        description: '4 turda bir, +savunma ve +iyileşme',
        fullDescription: 'Güneş ışığı ile kendini korur ve iyileştirir.',
      },
    ],
  },
}

// ============= ULTIMATE ABILITIES =============

export const ULTIMATE_ABILITIES: Record<string, AbilityDefinition> = {
  meteor_strike: {
    id: 'meteor_strike',
    name: 'Meteor Düşüşü',
    icon: 'meteor',
    emoji: '☄️',
    kind: 'ultimate',
    category: 'ultimate',
    cooldown: 6,
    damageMultiplier: 2.5,
        statScaling: 'atk',
    effects: [],
    description: 'Devasa bir meteor saldırısı',
    fullDescription: 'Gökyüzünden dev meteoru indirerek muazzam hasar verir.',
  },

  extinction_event: {
    id: 'extinction_event',
    name: 'Soyu Tükenme Olayı',
    icon: 'extinction',
    emoji: '⚰️',
    kind: 'ultimate',
    category: 'ultimate',
    cooldown: 6,
    damageMultiplier: 2.0,
        statScaling: 'atk',
    effects: ['stop'],
    description: 'Devasa saldırı + durdurma efekti',
    fullDescription: 'Rakibi tamamen donduran bir enerji dalgası saldırısı.',
  },

  primal_rage: {
    id: 'primal_rage',
    name: 'İlkel Öfke',
    icon: 'rage',
    emoji: '🌋',
    kind: 'ultimate',
    category: 'ultimate',
    cooldown: 6,
    damageMultiplier: 2.3,
        statScaling: 'atk',
    effects: ['power'],
    description: 'Muazzam hasar + +hasar efekti',
    fullDescription: 'Tüm gücü açığa çıkarak muazzam hasar verir ve kendisini güçlendirir.',
  },

  dimensional_tear: {
    id: 'dimensional_tear',
    name: 'Boyutsal Kopuş',
    icon: 'tear',
    emoji: '🌀',
    kind: 'ultimate',
    category: 'ultimate',
    cooldown: 6,
    damageMultiplier: 1.8,
        statScaling: 'max_atk_spd',
    effects: ['stun'],
    description: 'Yüksek hasar + sersemletme efekti',
    fullDescription: 'Boyutlar arası bir kopuş açarak yüksek hasar ve sersemlik verir.',
  },

  velocity_surge: {
    id: 'velocity_surge',
    name: 'Hız Dalgası',
    icon: 'speed',
    emoji: '💥',
    kind: 'ultimate',
    category: 'ultimate',
    cooldown: 6,
    damageMultiplier: 2.2,
        statScaling: 'max_atk_spd',
    effects: ['speed'],
    description: 'Çok yüksek hasar + +hız',
    fullDescription: 'Hızının zirvesine çıkarak çok yüksek hasar verir.',
  },

  death_venom: {
    id: 'death_venom',
    name: 'Ölüm Zehiri',
    icon: 'poison',
    emoji: '☠️',
    kind: 'ultimate',
    category: 'ultimate',
    cooldown: 6,
    damageMultiplier: 1.5,
        statScaling: 'atk',
    effects: ['poison'],
    description: 'Hasar + zehir efekti (3 tur)',
    fullDescription: 'Ölümcül zehir taşır. Uzun süre zehir verir.',
  },

  tidal_wave: {
    id: 'tidal_wave',
    name: 'Tsunami',
    icon: 'tidal_wave',
    emoji: '🌊',
    kind: 'ultimate',
    category: 'ultimate',
    cooldown: 6,
    damageMultiplier: 2.4,
        statScaling: 'max_atk_def',
    effects: [],
    description: 'Devasa su dalgası, muazzam hasar',
    fullDescription: 'Devasa bir tsunami yaratır. Karşısındakine muazzam hasar verir.',
  },

  genesis: {
    id: 'genesis',
    name: 'Yaratılış',
    icon: 'genesis',
    emoji: '🌱',
    kind: 'ultimate',
    category: 'ultimate',
    cooldown: 6,
    damageMultiplier: 0,
        statScaling: 'def',
    effects: ['regen'],
    description: 'Kendini çok iyileştirir',
    fullDescription: 'Yaşamın kaynağından güç çekti. Kendini tam olarak iyileştirir.',
  },

  inferno: {
    id: 'inferno',
    name: 'Cehennem Ateşi',
    icon: 'inferno',
    emoji: '🔥',
    kind: 'ultimate',
    category: 'ultimate',
    cooldown: 6,
    damageMultiplier: 2.6,
        statScaling: 'atk',
    effects: [],
    description: 'Ateş fırtınası, en yüksek hasar',
    fullDescription: 'Gökyüzü ateşe döner. Muazzam hasar verir.',
  },

  apocalypse: {
    id: 'apocalypse',
    name: 'Kıyamet',
    icon: 'apocalypse',
    emoji: '💀',
    kind: 'ultimate',
    category: 'ultimate',
    cooldown: 6,
    damageMultiplier: 2.1,
        statScaling: 'atk',
    effects: ['paralyze'],
    description: 'Yüksek hasar + paralyze efekti',
    fullDescription: 'Dünyanın sonu gibi bir saldırı. Rakibi felç eder.',
  },
}

// ============= ENEMY ABILITIES =============
// Themed abilities for adventure enemies based on enemy type and adventure theme

export const ENEMY_ABILITIES: Record<string, AbilityDefinition> = {
  // FOREST ENEMIES - Insect/Small creature themed
  grasshopper_jump: {
    id: 'grasshopper_jump',
    name: 'Çekirge Sıçrayışı',
    icon: 'jump',
    emoji: '🦗',
    kind: 'attack',
    category: 'base',
    cooldown: 1,
    damageMultiplier: 0.7,
    statScaling: 'spd',
    effects: [],
    description: 'Hızlı atlama hareketi',
    fullDescription: 'Çekirge benzeri hızlı bir sıçrayış. Orta hasar verir.',
  },

  squirrel_bite: {
    id: 'squirrel_bite',
    name: 'Sincap Dişlemesi',
    icon: 'bite',
    emoji: '🐿️',
    kind: 'attack',
    category: 'base',
    cooldown: 0,
    damageMultiplier: 0.6,
    statScaling: 'atk',
    effects: [],
    description: 'Hızlı ısırma hareketi',
    fullDescription: 'Keskin dişlerle ısırır. Hafif hasar verir ama sık kullanılır.',
  },

  squirrel_scurry: {
    id: 'squirrel_scurry',
    name: 'Sincap Kaçışı',
    icon: 'dodge',
    emoji: '💨',
    kind: 'buff',
    category: 'base',
    cooldown: 2,
    damageMultiplier: 0,
    statScaling: 'fixed',
    effects: ['speed'],
    description: '2 turda bir, hız buffı',
    fullDescription: 'Hızla kaçıp hız kazanır.',
  },

  iguana_bite: {
    id: 'iguana_bite',
    name: 'İguanadı Işırma',
    icon: 'bite',
    emoji: '🦎',
    kind: 'attack',
    category: 'base',
    cooldown: 2,
    damageMultiplier: 1.0,
    statScaling: 'atk',
    effects: ['poison'],
    description: '2 turda bir, hasar + zehir',
    fullDescription: 'Zehirli ısırma. Zehir efekti uygular.',
  },

  iguana_tail_swipe: {
    id: 'iguana_tail_swipe',
    name: 'İguanadı Kuyruk Darbesi',
    icon: 'tail',
    emoji: '💫',
    kind: 'attack',
    category: 'base',
    cooldown: 1,
    damageMultiplier: 0.8,
    statScaling: 'max_atk_def',
    effects: [],
    description: '1 turda bir, orta hasar',
    fullDescription: 'Kuvvetli kuyruk darbesi.',
  },

  // MOUNTAIN ENEMIES - Speed/Eagle themed
  eagle_swoop: {
    id: 'eagle_swoop',
    name: 'Kartal Daldırması',
    icon: 'dive',
    emoji: '🦅',
    kind: 'attack',
    category: 'base',
    cooldown: 1,
    damageMultiplier: 1.1,
    statScaling: 'max_atk_spd',
    effects: [],
    description: '1 turda bir, yüksek hasar',
    fullDescription: 'Hızlı daldırma hareketine gelen saldırı.',
  },

  eagle_screech: {
    id: 'eagle_screech',
    name: 'Kartal Çığlığı',
    icon: 'roar',
    emoji: '📢',
    kind: 'debuff',
    category: 'base',
    cooldown: 2,
    damageMultiplier: 0,
    statScaling: 'fixed',
    effects: ['stun'],
    description: '2 turda bir, sersemletme efekti',
    fullDescription: 'Yüksek ve korkutucu bir çığlık. Sersem eder.',
  },

  wolf_howl: {
    id: 'wolf_howl',
    name: 'Kurt Uluması',
    icon: 'roar',
    emoji: '🐺',
    kind: 'debuff',
    category: 'base',
    cooldown: 2,
    damageMultiplier: 0,
    statScaling: 'fixed',
    effects: ['defense_down'],
    description: '2 turda bir, savunma azalması',
    fullDescription: 'Ürkütücü bir uluma. Savunmayı düşürür.',
  },

  wolf_bite: {
    id: 'wolf_bite',
    name: 'Kurt Çakısı',
    icon: 'bite',
    emoji: '😈',
    kind: 'attack',
    category: 'base',
    cooldown: 1,
    damageMultiplier: 1.0,
    statScaling: 'atk',
    effects: ['bleeding'],
    description: '1 turda bir, hasar + kanama',
    fullDescription: 'Kanlı ısırma. Kanama efekti verir.',
  },

  deer_charge: {
    id: 'deer_charge',
    name: 'Geyik Çarptırması',
    icon: 'charge',
    emoji: '🦌',
    kind: 'attack',
    category: 'base',
    cooldown: 2,
    damageMultiplier: 1.2,
    statScaling: 'atk',
    effects: [],
    description: '2 turda bir, yüksek hasar',
    fullDescription: 'Boynuzla güçlü bir çarpma.',
  },

  deer_leap: {
    id: 'deer_leap',
    name: 'Geyik Sıçrayışı',
    icon: 'jump',
    emoji: '⚡',
    kind: 'buff',
    category: 'base',
    cooldown: 1,
    damageMultiplier: 0,
    statScaling: 'fixed',
    effects: ['speed'],
    description: '1 turda bir, hız buff',
    fullDescription: 'Hızlı bir sıçrayış ile hız kazanır.',
  },

  // SWAMP ENEMIES - Water/Reptile/Poison themed
  turtle_shell: {
    id: 'turtle_shell',
    name: 'Kaplumbağa Kabuğu',
    icon: 'shield',
    emoji: '🐢',
    kind: 'buff',
    category: 'base',
    cooldown: 2,
    damageMultiplier: 0,
    statScaling: 'fixed',
    effects: ['shield'],
    description: '2 turda bir, kalkan buff',
    fullDescription: 'Kabuğunun içine çekilerek kalkan oluşturur.',
  },

  turtle_bite: {
    id: 'turtle_bite',
    name: 'Kaplumbağa Isırması',
    icon: 'bite',
    emoji: '🦷',
    kind: 'attack',
    category: 'base',
    cooldown: 2,
    damageMultiplier: 1.1,
    statScaling: 'atk',
    effects: [],
    description: '2 turda bir, yüksek hasar',
    fullDescription: 'Güçlü bir ısırma hamlesi.',
  },

  crocodile_bite: {
    id: 'crocodile_bite',
    name: 'Timsah Çakısı',
    icon: 'bite',
    emoji: '🐊',
    kind: 'attack',
    category: 'base',
    cooldown: 1,
    damageMultiplier: 1.2,
    statScaling: 'atk',
    effects: ['bleeding'],
    description: '1 turda bir, yüksek hasar + kanama',
    fullDescription: 'Korkunç ve kanlı bir ısırma.',
  },

  crocodile_thrash: {
    id: 'crocodile_thrash',
    name: 'Timsah Çalkantısı',
    icon: 'attack',
    emoji: '💪',
    kind: 'attack',
    category: 'base',
    cooldown: 2,
    damageMultiplier: 1.3,
    statScaling: 'max_atk_def',
    effects: [],
    description: '2 turda bir, çok yüksek hasar',
    fullDescription: 'Güçlü kuyruk çalkanması.',
  },

  swamp_creature_poison: {
    id: 'swamp_creature_poison',
    name: 'Bataklık Zehri',
    icon: 'poison',
    emoji: '☠️',
    kind: 'debuff',
    category: 'base',
    cooldown: 2,
    damageMultiplier: 0.5,
    statScaling: 'atk',
    effects: ['poison'],
    description: '2 turda bir, hasar + zehir',
    fullDescription: 'Korkunç zehirli bir saldırı.',
  },

  // VOLCANO ENEMIES - Fire/Heat themed
  scorpion_sting: {
    id: 'scorpion_sting',
    name: 'Akrep Sokması',
    icon: 'poison',
    emoji: '🦂',
    kind: 'attack',
    category: 'base',
    cooldown: 1,
    damageMultiplier: 0.9,
    statScaling: 'atk',
    effects: ['poison'],
    description: '1 turda bir, hasar + zehir',
    fullDescription: 'Zehirli bir iğne sokması.',
  },

  scorpion_armor: {
    id: 'scorpion_armor',
    name: 'Akrep Zırhı',
    icon: 'shield',
    emoji: '🛡️',
    kind: 'buff',
    category: 'base',
    cooldown: 2,
    damageMultiplier: 0,
    statScaling: 'fixed',
    effects: ['shield'],
    description: '2 turda bir, kalkan buff',
    fullDescription: 'Dış kabuğu sertleştirerek koruma sağlar.',
  },

  fire_camel_spit: {
    id: 'fire_camel_spit',
    name: 'Ateş Devesi Tükürmesi',
    icon: 'spit',
    emoji: '🔥',
    kind: 'attack',
    category: 'base',
    cooldown: 1,
    damageMultiplier: 1.0,
    statScaling: 'max_atk_spd',
    effects: [],
    description: '1 turda bir, ateşli hasar',
    fullDescription: 'Sıcak sıvı püskürtme hamlesi.',
  },

  fire_camel_heat: {
    id: 'fire_camel_heat',
    name: 'Ateş Devesi Sıcağı',
    icon: 'fire',
    emoji: '🌡️',
    kind: 'debuff',
    category: 'base',
    cooldown: 2,
    damageMultiplier: 0.8,
    statScaling: 'atk',
    effects: [],
    description: '2 turda bir, orta hasar (sıcak)',
    fullDescription: 'Etrafı yakacak derecede ısıtır.',
  },

  dragon_bite: {
    id: 'dragon_bite',
    name: 'Volkan Dragonu Işırması',
    icon: 'bite',
    emoji: '🐉',
    kind: 'attack',
    category: 'base',
    cooldown: 1,
    damageMultiplier: 1.3,
    statScaling: 'atk',
    effects: [],
    description: '1 turda bir, çok yüksek hasar',
    fullDescription: 'Muazzam dişlerle ısırır.',
  },

  dragon_flame: {
    id: 'dragon_flame',
    name: 'Volkan Dragonu Ateş Nefesi',
    icon: 'fire',
    emoji: '🔥',
    kind: 'attack',
    category: 'base',
    cooldown: 2,
    damageMultiplier: 1.5,
    statScaling: 'atk',
    effects: [],
    description: '2 turda bir, en yüksek hasar',
    fullDescription: 'Korkunç ateş nefesi. Muazzam hasar verir.',
  },

  dragon_roar: {
    id: 'dragon_roar',
    name: 'Volkan Dragonu Bağırışı',
    icon: 'roar',
    emoji: '📣',
    kind: 'debuff',
    category: 'base',
    cooldown: 3,
    damageMultiplier: 0,
    statScaling: 'fixed',
    effects: ['stun'],
    description: '3 turda bir, sersemletme efekti',
    fullDescription: 'Yüksek ses çıkarma. Hedefi sersem eder.',
  },
}

// ============= HELPER FUNCTIONS =============

export function getClassAbilities(classId: string): ClassAbilities | undefined {
  return CLASS_ABILITIES[classId]
}

export function getSpecAbilities(specId: string): SpecAbilities | undefined {
  return SPEC_ABILITIES[specId]
}

export function getUltimateAbility(ultimateId: string): AbilityDefinition | undefined {
  return ULTIMATE_ABILITIES[ultimateId]
}

export function getAbilityDefinition(abilityId: string): AbilityDefinition | undefined {
  for (const classAbs of Object.values(CLASS_ABILITIES)) {
    const found = classAbs.abilities.find(a => a.id === abilityId)
    if (found) return found
  }

  for (const specAbs of Object.values(SPEC_ABILITIES)) {
    const found = specAbs.abilities.find(a => a.id === abilityId)
    if (found) return found
  }

  if (ULTIMATE_ABILITIES[abilityId]) return ULTIMATE_ABILITIES[abilityId]

  return ENEMY_ABILITIES[abilityId]
}

export function getAllClasses(): ClassAbilities[] {
  return Object.values(CLASS_ABILITIES)
}

export function getSpecsByClass(classId: string): SpecAbilities[] {
  return Object.values(SPEC_ABILITIES).filter(spec => spec.classId === classId)
}

export function getRandomAbilityFromList(abilities: AbilityDefinition[]): AbilityDefinition {
  return abilities[Math.floor(Math.random() * abilities.length)]
}

export function getUltimatesByClass(classId: string): AbilityDefinition[] {
  const validUltis = Object.values(ULTIMATE_ABILITIES)
  return validUltis
}
